name: Run the Windows build
on:
  workflow_dispatch: {}
  push:
    branches:
      - develop
      - main
jobs:
  build:
    name: Run the Windows build
    runs-on: ${{matrix.os}}
      strategy:
        matrix:
          os: [windows-latest,macos-latest]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      # Configure python
      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip PyInstaller

      - name: build
        run: pyinstaller gui.py --onefile --noconsole
  
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: gui-windows
          path: dist/gui.exe
